name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers only when you push to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Check PaperMod version
        run: |
          cd themes/PaperMod
          echo "Current PaperMod commit:"
          git log -1

      - name: Debug confirm schema_json exists
        run: |
          ls -al themes/PaperMod/layouts/partials/templates/

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'
          extended: true

      - name: Build site
        run: |
          hugo version
          hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
